#!/usr/bin/env node
// Generated by CoffeeScript 1.6.3
(function() {
  var client, colorName, config, formatHeading, fs, loadConfigOrDefault, main, needsReview, printActiveRequest, querystringify, rbapi;

  require('colors');

  querystringify = (require('querystring')).stringify;

  client = new (require('node-rest-client')).Client();

  fs = require('fs');

  config = {
    user: 'test',
    url: 'https://reviewboard.twitter.biz/',
    group: 'intl-eng-test'
  };

  main = function() {
    var filter;
    loadConfigOrDefault();
    filter = {
      status: 'pending',
      'to-groups': config.group
    };
    return rbapi('api/review-requests/', filter, function(res) {
      return res.review_requests.forEach(printActiveRequest);
    });
  };

  loadConfigOrDefault = function() {
    var config_path;
    config_path = process.env.HOME + '/.rbwhat.json';
    if (fs.existsSync(config_path)) {
      config = JSON.parse(fs.readFileSync(config_path).toString());
    } else {
      fs.writeFileSync(config_path, JSON.stringify(config, null, 2));
    }
    if (config.user === 'test') {
      return console.log('Set options in ~/.rbwhat.json');
    }
  };

  rbapi = function(path, args, cb) {
    var query;
    query = '?' + querystringify(args);
    return client.get(config.url + path + query, function(res) {
      return cb(JSON.parse(res));
    });
  };

  printActiveRequest = function(request) {
    var submitter;
    submitter = request.links.submitter.title;
    return rbapi("api/review-requests/" + request.id + "/reviews/", null, function(res) {
      var needs_review, output, review, reviewer, _i, _len, _ref;
      needs_review = config.user !== submitter;
      output = formatHeading(submitter, request);
      _ref = res.reviews;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        review = _ref[_i];
        reviewer = review.links.user.title;
        output.push('    ' + colorName(reviewer, submitter, review.ship_it));
        needs_review = needsReview(reviewer, submitter, needs_review);
      }
      if (needs_review) {
        return console.log(output.join('\n'));
      }
    });
  };

  formatHeading = function(submitter, request) {
    var url;
    url = "" + config.url + "r/" + request.id + "/diff";
    return ["" + (colorName(submitter, submitter)) + ": " + request.summary.yellow, "  " + url.underline];
  };

  colorName = function(name, submitter, shipit) {
    switch (name) {
      case config.user:
        return name.cyan;
      case submitter:
        return name.magenta;
      default:
        if (shipit) {
          return name.green;
        } else {
          return name.red;
        }
    }
  };

  needsReview = function(reviewer, submitter, needs_review) {
    if (config.user === reviewer) {
      return false;
    } else if (reviewer === submitter) {
      return true;
    } else if (submitter === config.user) {
      return true;
    } else {
      return needs_review;
    }
  };

  main();

}).call(this);
