#!/usr/bin/env node
// Generated by CoffeeScript 1.6.3
(function() {
  var args, client, colors, config, config_file, eachReviewRequest, fs, login_user, node_rest_client, querystring, rb, rbcall, util;

  colors = require('colors');

  util = require('util');

  querystring = require('querystring');

  node_rest_client = require('node-rest-client');

  fs = require('fs');

  config_file = process.argv[2];

  config_file || (config_file = process.env.HOME + '/.rbwhat.json');

  config = JSON.parse(fs.readFileSync(config_file).toString());

  client = new node_rest_client.Client({
    user: config.user,
    password: config.password
  });

  login_user = config.user;

  rb = config.url;

  rbcall = function(path, args, cb) {
    var query;
    query = '?' + querystring.stringify(args);
    return client.get(rb + path + query, function(res) {
      return cb(JSON.parse(res));
    });
  };

  args = {
    'status': 'pending'
  };

  if (config.group) {
    args['to-groups'] = config.group;
  }

  rbcall('api/review-requests/', args, function(res) {
    return res.review_requests.forEach(eachReviewRequest);
  });

  eachReviewRequest = function(request) {
    var submitter;
    submitter = request.links.submitter.title;
    return rbcall("api/review-requests/" + request.id + "/reviews/", null, function(res) {
      var colored_submitter, needs_review, output, review, reviewer, shipit, _i, _len, _ref;
      output = [];
      colored_submitter = submitter === login_user ? submitter.cyan : submitter.magenta;
      output.push(colored_submitter + ': ' + request.summary.yellow);
      output.push('  ' + ("" + rb + "r/" + request.id + "/diff").underline);
      needs_review = login_user === submitter ? false : true;
      _ref = res.reviews;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        review = _ref[_i];
        reviewer = review.links.user.title;
        shipit = review.ship_it;
        output.push('    ' + (reviewer === login_user ? reviewer.cyan : reviewer === submitter ? reviewer.magenta : shipit ? reviewer.green : reviewer.red));
        if (login_user === reviewer) {
          needs_review = false;
        } else if (reviewer === submitter) {
          needs_review = true;
        } else if (submitter === login_user) {
          needs_review = true;
        }
      }
      if (needs_review) {
        return console.log(output.join('\n'));
      }
    });
  };

}).call(this);
